#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawspot.Backend
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Lawspot")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRegion(Region instance);
    partial void UpdateRegion(Region instance);
    partial void DeleteRegion(Region instance);
    partial void InsertMigration(Migration instance);
    partial void UpdateMigration(Migration instance);
    partial void DeleteMigration(Migration instance);
    partial void InsertDraftAnswer(DraftAnswer instance);
    partial void UpdateDraftAnswer(DraftAnswer instance);
    partial void DeleteDraftAnswer(DraftAnswer instance);
    partial void InsertCategory(Category instance);
    partial void UpdateCategory(Category instance);
    partial void DeleteCategory(Category instance);
    partial void InsertLawyer(Lawyer instance);
    partial void UpdateLawyer(Lawyer instance);
    partial void DeleteLawyer(Lawyer instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertQuestion(Question instance);
    partial void UpdateQuestion(Question instance);
    partial void DeleteQuestion(Question instance);
    partial void InsertAnswer(Answer instance);
    partial void UpdateAnswer(Answer instance);
    partial void DeleteAnswer(Answer instance);
    partial void InsertPublisher(Publisher instance);
    partial void UpdatePublisher(Publisher instance);
    partial void DeletePublisher(Publisher instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LawspotConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Region> Regions
		{
			get
			{
				return this.GetTable<Region>();
			}
		}
		
		public System.Data.Linq.Table<Migration> Migrations
		{
			get
			{
				return this.GetTable<Migration>();
			}
		}
		
		public System.Data.Linq.Table<DraftAnswer> DraftAnswers
		{
			get
			{
				return this.GetTable<DraftAnswer>();
			}
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<Lawyer> Lawyers
		{
			get
			{
				return this.GetTable<Lawyer>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Question> Questions
		{
			get
			{
				return this.GetTable<Question>();
			}
		}
		
		public System.Data.Linq.Table<Answer> Answers
		{
			get
			{
				return this.GetTable<Answer>();
			}
		}
		
		public System.Data.Linq.Table<Publisher> Publishers
		{
			get
			{
				return this.GetTable<Publisher>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Region")]
	public partial class Region : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RegionId;
		
		private string _Name;
		
		private EntitySet<User> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegionIdChanging(int value);
    partial void OnRegionIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Region()
		{
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RegionId
		{
			get
			{
				return this._RegionId;
			}
			set
			{
				if ((this._RegionId != value))
				{
					this.OnRegionIdChanging(value);
					this.SendPropertyChanging();
					this._RegionId = value;
					this.SendPropertyChanged("RegionId");
					this.OnRegionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Region_User", Storage="_Users", ThisKey="RegionId", OtherKey="RegionId")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Region = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Region = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Migrations")]
	public partial class Migration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MigrationId;
		
		private int _Version;
		
		private System.DateTimeOffset _RunAt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMigrationIdChanging(int value);
    partial void OnMigrationIdChanged();
    partial void OnVersionChanging(int value);
    partial void OnVersionChanged();
    partial void OnRunAtChanging(System.DateTimeOffset value);
    partial void OnRunAtChanged();
    #endregion
		
		public Migration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MigrationId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MigrationId
		{
			get
			{
				return this._MigrationId;
			}
			set
			{
				if ((this._MigrationId != value))
				{
					this.OnMigrationIdChanging(value);
					this.SendPropertyChanging();
					this._MigrationId = value;
					this.SendPropertyChanged("MigrationId");
					this.OnMigrationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="Int NOT NULL")]
		public int Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunAt", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset RunAt
		{
			get
			{
				return this._RunAt;
			}
			set
			{
				if ((this._RunAt != value))
				{
					this.OnRunAtChanging(value);
					this.SendPropertyChanging();
					this._RunAt = value;
					this.SendPropertyChanged("RunAt");
					this.OnRunAtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DraftAnswer")]
	public partial class DraftAnswer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DraftAnswerId;
		
		private int _QuestionId;
		
		private string _Details;
		
		private string _References;
		
		private System.DateTimeOffset _CreatedOn;
		
		private int _CreatedByUserId;
		
		private System.DateTimeOffset _UpdatedOn;
		
		private EntityRef<User> _User;
		
		private EntityRef<Question> _Question;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDraftAnswerIdChanging(int value);
    partial void OnDraftAnswerIdChanged();
    partial void OnQuestionIdChanging(int value);
    partial void OnQuestionIdChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnReferencesChanging(string value);
    partial void OnReferencesChanged();
    partial void OnCreatedOnChanging(System.DateTimeOffset value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByUserIdChanging(int value);
    partial void OnCreatedByUserIdChanged();
    partial void OnUpdatedOnChanging(System.DateTimeOffset value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public DraftAnswer()
		{
			this._User = default(EntityRef<User>);
			this._Question = default(EntityRef<Question>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DraftAnswerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DraftAnswerId
		{
			get
			{
				return this._DraftAnswerId;
			}
			set
			{
				if ((this._DraftAnswerId != value))
				{
					this.OnDraftAnswerIdChanging(value);
					this.SendPropertyChanging();
					this._DraftAnswerId = value;
					this.SendPropertyChanged("DraftAnswerId");
					this.OnDraftAnswerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int NOT NULL")]
		public int QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					if (this._Question.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQuestionIdChanging(value);
					this.SendPropertyChanging();
					this._QuestionId = value;
					this.SendPropertyChanged("QuestionId");
					this.OnQuestionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[References]", Storage="_References", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string References
		{
			get
			{
				return this._References;
			}
			set
			{
				if ((this._References != value))
				{
					this.OnReferencesChanging(value);
					this.SendPropertyChanging();
					this._References = value;
					this.SendPropertyChanged("References");
					this.OnReferencesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserId", DbType="Int NOT NULL")]
		public int CreatedByUserId
		{
			get
			{
				return this._CreatedByUserId;
			}
			set
			{
				if ((this._CreatedByUserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCreatedByUserIdChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserId = value;
					this.SendPropertyChanged("CreatedByUserId");
					this.OnCreatedByUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_DraftAnswer", Storage="_User", ThisKey="CreatedByUserId", OtherKey="UserId", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.DraftAnswers.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.DraftAnswers.Add(this);
						this._CreatedByUserId = value.UserId;
					}
					else
					{
						this._CreatedByUserId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Question_DraftAnswer", Storage="_Question", ThisKey="QuestionId", OtherKey="QuestionId", IsForeignKey=true)]
		public Question Question
		{
			get
			{
				return this._Question.Entity;
			}
			set
			{
				Question previousValue = this._Question.Entity;
				if (((previousValue != value) 
							|| (this._Question.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Question.Entity = null;
						previousValue.DraftAnswers.Remove(this);
					}
					this._Question.Entity = value;
					if ((value != null))
					{
						value.DraftAnswers.Add(this);
						this._QuestionId = value.QuestionId;
					}
					else
					{
						this._QuestionId = default(int);
					}
					this.SendPropertyChanged("Question");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoryId;
		
		private string _Name;
		
		private string _Slug;
		
		private int _ApprovedQuestionCount;
		
		private int _AnsweredQuestionCount;
		
		private EntitySet<Lawyer> _Lawyers;
		
		private EntitySet<Question> _Questions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIdChanging(int value);
    partial void OnCategoryIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSlugChanging(string value);
    partial void OnSlugChanged();
    partial void OnApprovedQuestionCountChanging(int value);
    partial void OnApprovedQuestionCountChanged();
    partial void OnAnsweredQuestionCountChanging(int value);
    partial void OnAnsweredQuestionCountChanged();
    #endregion
		
		public Category()
		{
			this._Lawyers = new EntitySet<Lawyer>(new Action<Lawyer>(this.attach_Lawyers), new Action<Lawyer>(this.detach_Lawyers));
			this._Questions = new EntitySet<Question>(new Action<Question>(this.attach_Questions), new Action<Question>(this.detach_Questions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slug", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Slug
		{
			get
			{
				return this._Slug;
			}
			set
			{
				if ((this._Slug != value))
				{
					this.OnSlugChanging(value);
					this.SendPropertyChanging();
					this._Slug = value;
					this.SendPropertyChanged("Slug");
					this.OnSlugChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedQuestionCount", DbType="Int NOT NULL")]
		public int ApprovedQuestionCount
		{
			get
			{
				return this._ApprovedQuestionCount;
			}
			set
			{
				if ((this._ApprovedQuestionCount != value))
				{
					this.OnApprovedQuestionCountChanging(value);
					this.SendPropertyChanging();
					this._ApprovedQuestionCount = value;
					this.SendPropertyChanged("ApprovedQuestionCount");
					this.OnApprovedQuestionCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnsweredQuestionCount", DbType="Int NOT NULL")]
		public int AnsweredQuestionCount
		{
			get
			{
				return this._AnsweredQuestionCount;
			}
			set
			{
				if ((this._AnsweredQuestionCount != value))
				{
					this.OnAnsweredQuestionCountChanging(value);
					this.SendPropertyChanging();
					this._AnsweredQuestionCount = value;
					this.SendPropertyChanged("AnsweredQuestionCount");
					this.OnAnsweredQuestionCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Lawyer", Storage="_Lawyers", ThisKey="CategoryId", OtherKey="SpecialisationCategoryId")]
		public EntitySet<Lawyer> Lawyers
		{
			get
			{
				return this._Lawyers;
			}
			set
			{
				this._Lawyers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Question", Storage="_Questions", ThisKey="CategoryId", OtherKey="CategoryId")]
		public EntitySet<Question> Questions
		{
			get
			{
				return this._Questions;
			}
			set
			{
				this._Questions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lawyers(Lawyer entity)
		{
			this.SendPropertyChanging();
			entity.Category = this;
		}
		
		private void detach_Lawyers(Lawyer entity)
		{
			this.SendPropertyChanging();
			entity.Category = null;
		}
		
		private void attach_Questions(Question entity)
		{
			this.SendPropertyChanging();
			entity.Category = this;
		}
		
		private void detach_Questions(Question entity)
		{
			this.SendPropertyChanging();
			entity.Category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lawyer")]
	public partial class Lawyer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LawyerId;
		
		private int _UserId;
		
		private string _FirstName;
		
		private string _LastName;
		
		private int _YearOfAdmission;
		
		private System.Nullable<int> _SpecialisationCategoryId;
		
		private string _EmployerName;
		
		private System.DateTimeOffset _CreatedOn;
		
		private bool _Approved;
		
		private System.Nullable<System.DateTimeOffset> _ReviewDate;
		
		private System.Nullable<int> _ReviewedByUserId;
		
		private string _RejectionReason;
		
		private EntityRef<Category> _Category;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLawyerIdChanging(int value);
    partial void OnLawyerIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnYearOfAdmissionChanging(int value);
    partial void OnYearOfAdmissionChanged();
    partial void OnSpecialisationCategoryIdChanging(System.Nullable<int> value);
    partial void OnSpecialisationCategoryIdChanged();
    partial void OnEmployerNameChanging(string value);
    partial void OnEmployerNameChanged();
    partial void OnCreatedOnChanging(System.DateTimeOffset value);
    partial void OnCreatedOnChanged();
    partial void OnApprovedChanging(bool value);
    partial void OnApprovedChanged();
    partial void OnReviewDateChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnReviewDateChanged();
    partial void OnReviewedByUserIdChanging(System.Nullable<int> value);
    partial void OnReviewedByUserIdChanged();
    partial void OnRejectionReasonChanging(string value);
    partial void OnRejectionReasonChanged();
    #endregion
		
		public Lawyer()
		{
			this._Category = default(EntityRef<Category>);
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LawyerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LawyerId
		{
			get
			{
				return this._LawyerId;
			}
			set
			{
				if ((this._LawyerId != value))
				{
					this.OnLawyerIdChanging(value);
					this.SendPropertyChanging();
					this._LawyerId = value;
					this.SendPropertyChanged("LawyerId");
					this.OnLawyerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearOfAdmission", DbType="Int NOT NULL")]
		public int YearOfAdmission
		{
			get
			{
				return this._YearOfAdmission;
			}
			set
			{
				if ((this._YearOfAdmission != value))
				{
					this.OnYearOfAdmissionChanging(value);
					this.SendPropertyChanging();
					this._YearOfAdmission = value;
					this.SendPropertyChanged("YearOfAdmission");
					this.OnYearOfAdmissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecialisationCategoryId", DbType="Int")]
		public System.Nullable<int> SpecialisationCategoryId
		{
			get
			{
				return this._SpecialisationCategoryId;
			}
			set
			{
				if ((this._SpecialisationCategoryId != value))
				{
					if (this._Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSpecialisationCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._SpecialisationCategoryId = value;
					this.SendPropertyChanged("SpecialisationCategoryId");
					this.OnSpecialisationCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployerName", DbType="NVarChar(100)")]
		public string EmployerName
		{
			get
			{
				return this._EmployerName;
			}
			set
			{
				if ((this._EmployerName != value))
				{
					this.OnEmployerNameChanging(value);
					this.SendPropertyChanging();
					this._EmployerName = value;
					this.SendPropertyChanged("EmployerName");
					this.OnEmployerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approved", DbType="Bit NOT NULL")]
		public bool Approved
		{
			get
			{
				return this._Approved;
			}
			set
			{
				if ((this._Approved != value))
				{
					this.OnApprovedChanging(value);
					this.SendPropertyChanging();
					this._Approved = value;
					this.SendPropertyChanged("Approved");
					this.OnApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewDate", DbType="DateTimeOffset")]
		public System.Nullable<System.DateTimeOffset> ReviewDate
		{
			get
			{
				return this._ReviewDate;
			}
			set
			{
				if ((this._ReviewDate != value))
				{
					this.OnReviewDateChanging(value);
					this.SendPropertyChanging();
					this._ReviewDate = value;
					this.SendPropertyChanged("ReviewDate");
					this.OnReviewDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewedByUserId", DbType="Int")]
		public System.Nullable<int> ReviewedByUserId
		{
			get
			{
				return this._ReviewedByUserId;
			}
			set
			{
				if ((this._ReviewedByUserId != value))
				{
					this.OnReviewedByUserIdChanging(value);
					this.SendPropertyChanging();
					this._ReviewedByUserId = value;
					this.SendPropertyChanged("ReviewedByUserId");
					this.OnReviewedByUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectionReason", DbType="NVarChar(MAX)")]
		public string RejectionReason
		{
			get
			{
				return this._RejectionReason;
			}
			set
			{
				if ((this._RejectionReason != value))
				{
					this.OnRejectionReasonChanging(value);
					this.SendPropertyChanging();
					this._RejectionReason = value;
					this.SendPropertyChanged("RejectionReason");
					this.OnRejectionReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Lawyer", Storage="_Category", ThisKey="SpecialisationCategoryId", OtherKey="CategoryId", IsForeignKey=true)]
		public Category Category
		{
			get
			{
				return this._Category.Entity;
			}
			set
			{
				Category previousValue = this._Category.Entity;
				if (((previousValue != value) 
							|| (this._Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Category.Entity = null;
						previousValue.Lawyers.Remove(this);
					}
					this._Category.Entity = value;
					if ((value != null))
					{
						value.Lawyers.Add(this);
						this._SpecialisationCategoryId = value.CategoryId;
					}
					else
					{
						this._SpecialisationCategoryId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Category");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Lawyer", Storage="_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
		public User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.Lawyers.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.Lawyers.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserId;
		
		private string _EmailAddress;
		
		private string _Password;
		
		private int _RegionId;
		
		private System.DateTimeOffset _CreatedOn;
		
		private bool _CanAnswerQuestions;
		
		private bool _CanVetQuestions;
		
		private bool _CanVetAnswers;
		
		private bool _CanVetLawyers;
		
		private bool _CanAdminister;
		
		private System.Nullable<System.DateTimeOffset> _LastLogInDate;
		
		private int _LogInCount;
		
		private string _LogInIpAddress;
		
		private System.Nullable<int> _CommunityServicesCardNumber;
		
		private System.Nullable<bool> _EmailValidated;
		
		private string _EmailValidationToken;
		
		private string _ResetPasswordToken;
		
		private System.Nullable<System.DateTimeOffset> _ResetPasswordTokenExpiry;
		
		private System.Nullable<int> _PublisherId;
		
		private EntitySet<DraftAnswer> _DraftAnswers;
		
		private EntitySet<Lawyer> _Lawyers;
		
		private EntitySet<Question> _CreatedQuestions;
		
		private EntitySet<Question> _ReviewedQuestions;
		
		private EntitySet<Answer> _CreatedAnswers;
		
		private EntitySet<Answer> _ReviewedAnswers;
		
		private EntityRef<Region> _Region;
		
		private EntityRef<Publisher> _Publisher;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRegionIdChanging(int value);
    partial void OnRegionIdChanged();
    partial void OnCreatedOnChanging(System.DateTimeOffset value);
    partial void OnCreatedOnChanged();
    partial void OnCanAnswerQuestionsChanging(bool value);
    partial void OnCanAnswerQuestionsChanged();
    partial void OnCanVetQuestionsChanging(bool value);
    partial void OnCanVetQuestionsChanged();
    partial void OnCanVetAnswersChanging(bool value);
    partial void OnCanVetAnswersChanged();
    partial void OnCanVetLawyersChanging(bool value);
    partial void OnCanVetLawyersChanged();
    partial void OnCanAdministerChanging(bool value);
    partial void OnCanAdministerChanged();
    partial void OnLastLogInDateChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnLastLogInDateChanged();
    partial void OnLogInCountChanging(int value);
    partial void OnLogInCountChanged();
    partial void OnLogInIpAddressChanging(string value);
    partial void OnLogInIpAddressChanged();
    partial void OnCommunityServicesCardNumberChanging(System.Nullable<int> value);
    partial void OnCommunityServicesCardNumberChanged();
    partial void OnEmailValidatedChanging(System.Nullable<bool> value);
    partial void OnEmailValidatedChanged();
    partial void OnEmailValidationTokenChanging(string value);
    partial void OnEmailValidationTokenChanged();
    partial void OnResetPasswordTokenChanging(string value);
    partial void OnResetPasswordTokenChanged();
    partial void OnResetPasswordTokenExpiryChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnResetPasswordTokenExpiryChanged();
    partial void OnPublisherIdChanging(System.Nullable<int> value);
    partial void OnPublisherIdChanged();
    #endregion
		
		public User()
		{
			this._DraftAnswers = new EntitySet<DraftAnswer>(new Action<DraftAnswer>(this.attach_DraftAnswers), new Action<DraftAnswer>(this.detach_DraftAnswers));
			this._Lawyers = new EntitySet<Lawyer>(new Action<Lawyer>(this.attach_Lawyers), new Action<Lawyer>(this.detach_Lawyers));
			this._CreatedQuestions = new EntitySet<Question>(new Action<Question>(this.attach_CreatedQuestions), new Action<Question>(this.detach_CreatedQuestions));
			this._ReviewedQuestions = new EntitySet<Question>(new Action<Question>(this.attach_ReviewedQuestions), new Action<Question>(this.detach_ReviewedQuestions));
			this._CreatedAnswers = new EntitySet<Answer>(new Action<Answer>(this.attach_CreatedAnswers), new Action<Answer>(this.detach_CreatedAnswers));
			this._ReviewedAnswers = new EntitySet<Answer>(new Action<Answer>(this.attach_ReviewedAnswers), new Action<Answer>(this.detach_ReviewedAnswers));
			this._Region = default(EntityRef<Region>);
			this._Publisher = default(EntityRef<Publisher>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegionId", DbType="Int NOT NULL")]
		public int RegionId
		{
			get
			{
				return this._RegionId;
			}
			set
			{
				if ((this._RegionId != value))
				{
					if (this._Region.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRegionIdChanging(value);
					this.SendPropertyChanging();
					this._RegionId = value;
					this.SendPropertyChanged("RegionId");
					this.OnRegionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanAnswerQuestions", DbType="Bit NOT NULL")]
		public bool CanAnswerQuestions
		{
			get
			{
				return this._CanAnswerQuestions;
			}
			set
			{
				if ((this._CanAnswerQuestions != value))
				{
					this.OnCanAnswerQuestionsChanging(value);
					this.SendPropertyChanging();
					this._CanAnswerQuestions = value;
					this.SendPropertyChanged("CanAnswerQuestions");
					this.OnCanAnswerQuestionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanVetQuestions", DbType="Bit NOT NULL")]
		public bool CanVetQuestions
		{
			get
			{
				return this._CanVetQuestions;
			}
			set
			{
				if ((this._CanVetQuestions != value))
				{
					this.OnCanVetQuestionsChanging(value);
					this.SendPropertyChanging();
					this._CanVetQuestions = value;
					this.SendPropertyChanged("CanVetQuestions");
					this.OnCanVetQuestionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanVetAnswers", DbType="Bit NOT NULL")]
		public bool CanVetAnswers
		{
			get
			{
				return this._CanVetAnswers;
			}
			set
			{
				if ((this._CanVetAnswers != value))
				{
					this.OnCanVetAnswersChanging(value);
					this.SendPropertyChanging();
					this._CanVetAnswers = value;
					this.SendPropertyChanged("CanVetAnswers");
					this.OnCanVetAnswersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanVetLawyers", DbType="Bit NOT NULL")]
		public bool CanVetLawyers
		{
			get
			{
				return this._CanVetLawyers;
			}
			set
			{
				if ((this._CanVetLawyers != value))
				{
					this.OnCanVetLawyersChanging(value);
					this.SendPropertyChanging();
					this._CanVetLawyers = value;
					this.SendPropertyChanged("CanVetLawyers");
					this.OnCanVetLawyersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanAdminister", DbType="Bit NOT NULL")]
		public bool CanAdminister
		{
			get
			{
				return this._CanAdminister;
			}
			set
			{
				if ((this._CanAdminister != value))
				{
					this.OnCanAdministerChanging(value);
					this.SendPropertyChanging();
					this._CanAdminister = value;
					this.SendPropertyChanged("CanAdminister");
					this.OnCanAdministerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLogInDate", DbType="DateTimeOffset")]
		public System.Nullable<System.DateTimeOffset> LastLogInDate
		{
			get
			{
				return this._LastLogInDate;
			}
			set
			{
				if ((this._LastLogInDate != value))
				{
					this.OnLastLogInDateChanging(value);
					this.SendPropertyChanging();
					this._LastLogInDate = value;
					this.SendPropertyChanged("LastLogInDate");
					this.OnLastLogInDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogInCount", DbType="Int NOT NULL")]
		public int LogInCount
		{
			get
			{
				return this._LogInCount;
			}
			set
			{
				if ((this._LogInCount != value))
				{
					this.OnLogInCountChanging(value);
					this.SendPropertyChanging();
					this._LogInCount = value;
					this.SendPropertyChanged("LogInCount");
					this.OnLogInCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogInIpAddress", DbType="VarChar(45)")]
		public string LogInIpAddress
		{
			get
			{
				return this._LogInIpAddress;
			}
			set
			{
				if ((this._LogInIpAddress != value))
				{
					this.OnLogInIpAddressChanging(value);
					this.SendPropertyChanging();
					this._LogInIpAddress = value;
					this.SendPropertyChanged("LogInIpAddress");
					this.OnLogInIpAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommunityServicesCardNumber", DbType="Int")]
		public System.Nullable<int> CommunityServicesCardNumber
		{
			get
			{
				return this._CommunityServicesCardNumber;
			}
			set
			{
				if ((this._CommunityServicesCardNumber != value))
				{
					this.OnCommunityServicesCardNumberChanging(value);
					this.SendPropertyChanging();
					this._CommunityServicesCardNumber = value;
					this.SendPropertyChanged("CommunityServicesCardNumber");
					this.OnCommunityServicesCardNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailValidated", DbType="Bit")]
		public System.Nullable<bool> EmailValidated
		{
			get
			{
				return this._EmailValidated;
			}
			set
			{
				if ((this._EmailValidated != value))
				{
					this.OnEmailValidatedChanging(value);
					this.SendPropertyChanging();
					this._EmailValidated = value;
					this.SendPropertyChanged("EmailValidated");
					this.OnEmailValidatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailValidationToken", DbType="VarChar(50)")]
		public string EmailValidationToken
		{
			get
			{
				return this._EmailValidationToken;
			}
			set
			{
				if ((this._EmailValidationToken != value))
				{
					this.OnEmailValidationTokenChanging(value);
					this.SendPropertyChanging();
					this._EmailValidationToken = value;
					this.SendPropertyChanged("EmailValidationToken");
					this.OnEmailValidationTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResetPasswordToken", DbType="VarChar(50)")]
		public string ResetPasswordToken
		{
			get
			{
				return this._ResetPasswordToken;
			}
			set
			{
				if ((this._ResetPasswordToken != value))
				{
					this.OnResetPasswordTokenChanging(value);
					this.SendPropertyChanging();
					this._ResetPasswordToken = value;
					this.SendPropertyChanged("ResetPasswordToken");
					this.OnResetPasswordTokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResetPasswordTokenExpiry", DbType="DateTimeOffset")]
		public System.Nullable<System.DateTimeOffset> ResetPasswordTokenExpiry
		{
			get
			{
				return this._ResetPasswordTokenExpiry;
			}
			set
			{
				if ((this._ResetPasswordTokenExpiry != value))
				{
					this.OnResetPasswordTokenExpiryChanging(value);
					this.SendPropertyChanging();
					this._ResetPasswordTokenExpiry = value;
					this.SendPropertyChanged("ResetPasswordTokenExpiry");
					this.OnResetPasswordTokenExpiryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublisherId")]
		public System.Nullable<int> PublisherId
		{
			get
			{
				return this._PublisherId;
			}
			set
			{
				if ((this._PublisherId != value))
				{
					if (this._Publisher.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPublisherIdChanging(value);
					this.SendPropertyChanging();
					this._PublisherId = value;
					this.SendPropertyChanged("PublisherId");
					this.OnPublisherIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_DraftAnswer", Storage="_DraftAnswers", ThisKey="UserId", OtherKey="CreatedByUserId")]
		public EntitySet<DraftAnswer> DraftAnswers
		{
			get
			{
				return this._DraftAnswers;
			}
			set
			{
				this._DraftAnswers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Lawyer", Storage="_Lawyers", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<Lawyer> Lawyers
		{
			get
			{
				return this._Lawyers;
			}
			set
			{
				this._Lawyers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Question", Storage="_CreatedQuestions", ThisKey="UserId", OtherKey="CreatedByUserId")]
		public EntitySet<Question> CreatedQuestions
		{
			get
			{
				return this._CreatedQuestions;
			}
			set
			{
				this._CreatedQuestions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Question1", Storage="_ReviewedQuestions", ThisKey="UserId", OtherKey="ReviewedByUserId")]
		public EntitySet<Question> ReviewedQuestions
		{
			get
			{
				return this._ReviewedQuestions;
			}
			set
			{
				this._ReviewedQuestions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Answer", Storage="_CreatedAnswers", ThisKey="UserId", OtherKey="CreatedByUserId")]
		public EntitySet<Answer> CreatedAnswers
		{
			get
			{
				return this._CreatedAnswers;
			}
			set
			{
				this._CreatedAnswers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Answer1", Storage="_ReviewedAnswers", ThisKey="UserId", OtherKey="ReviewedByUserId")]
		public EntitySet<Answer> ReviewedAnswers
		{
			get
			{
				return this._ReviewedAnswers;
			}
			set
			{
				this._ReviewedAnswers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Region_User", Storage="_Region", ThisKey="RegionId", OtherKey="RegionId", IsForeignKey=true)]
		public Region Region
		{
			get
			{
				return this._Region.Entity;
			}
			set
			{
				Region previousValue = this._Region.Entity;
				if (((previousValue != value) 
							|| (this._Region.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Region.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._Region.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._RegionId = value.RegionId;
					}
					else
					{
						this._RegionId = default(int);
					}
					this.SendPropertyChanged("Region");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publisher_User", Storage="_Publisher", ThisKey="PublisherId", OtherKey="PublisherId", IsForeignKey=true)]
		public Publisher Publisher
		{
			get
			{
				return this._Publisher.Entity;
			}
			set
			{
				Publisher previousValue = this._Publisher.Entity;
				if (((previousValue != value) 
							|| (this._Publisher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Publisher.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._Publisher.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._PublisherId = value.PublisherId;
					}
					else
					{
						this._PublisherId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Publisher");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DraftAnswers(DraftAnswer entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_DraftAnswers(DraftAnswer entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_Lawyers(Lawyer entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_Lawyers(Lawyer entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_CreatedQuestions(Question entity)
		{
			this.SendPropertyChanging();
			entity.CreatedByUser = this;
		}
		
		private void detach_CreatedQuestions(Question entity)
		{
			this.SendPropertyChanging();
			entity.CreatedByUser = null;
		}
		
		private void attach_ReviewedQuestions(Question entity)
		{
			this.SendPropertyChanging();
			entity.ReviewedByUser = this;
		}
		
		private void detach_ReviewedQuestions(Question entity)
		{
			this.SendPropertyChanging();
			entity.ReviewedByUser = null;
		}
		
		private void attach_CreatedAnswers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.CreatedByUser = this;
		}
		
		private void detach_CreatedAnswers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.CreatedByUser = null;
		}
		
		private void attach_ReviewedAnswers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.ReviewedByUser = this;
		}
		
		private void detach_ReviewedAnswers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.ReviewedByUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Question")]
	public partial class Question : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _QuestionId;
		
		private string _Title;
		
		private string _Details;
		
		private int _CategoryId;
		
		private System.DateTimeOffset _CreatedOn;
		
		private int _CreatedByUserId;
		
		private int _ViewCount;
		
		private string _Slug;
		
		private bool _Approved;
		
		private System.Nullable<System.DateTimeOffset> _ReviewDate;
		
		private System.Nullable<int> _ReviewedByUserId;
		
		private string _RejectionReason;
		
		private string _OriginalTitle;
		
		private string _OriginalDetails;
		
		private EntitySet<DraftAnswer> _DraftAnswers;
		
		private EntitySet<Answer> _Answers;
		
		private EntityRef<Category> _Category;
		
		private EntityRef<User> _CreatedByUser;
		
		private EntityRef<User> _ReviewedByUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestionIdChanging(int value);
    partial void OnQuestionIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnCategoryIdChanging(int value);
    partial void OnCategoryIdChanged();
    partial void OnCreatedOnChanging(System.DateTimeOffset value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByUserIdChanging(int value);
    partial void OnCreatedByUserIdChanged();
    partial void OnViewCountChanging(int value);
    partial void OnViewCountChanged();
    partial void OnSlugChanging(string value);
    partial void OnSlugChanged();
    partial void OnApprovedChanging(bool value);
    partial void OnApprovedChanged();
    partial void OnReviewDateChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnReviewDateChanged();
    partial void OnReviewedByUserIdChanging(System.Nullable<int> value);
    partial void OnReviewedByUserIdChanged();
    partial void OnRejectionReasonChanging(string value);
    partial void OnRejectionReasonChanged();
    partial void OnOriginalTitleChanging(string value);
    partial void OnOriginalTitleChanged();
    partial void OnOriginalDetailsChanging(string value);
    partial void OnOriginalDetailsChanged();
    #endregion
		
		public Question()
		{
			this._DraftAnswers = new EntitySet<DraftAnswer>(new Action<DraftAnswer>(this.attach_DraftAnswers), new Action<DraftAnswer>(this.detach_DraftAnswers));
			this._Answers = new EntitySet<Answer>(new Action<Answer>(this.attach_Answers), new Action<Answer>(this.detach_Answers));
			this._Category = default(EntityRef<Category>);
			this._CreatedByUser = default(EntityRef<User>);
			this._ReviewedByUser = default(EntityRef<User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this.OnQuestionIdChanging(value);
					this.SendPropertyChanging();
					this._QuestionId = value;
					this.SendPropertyChanged("QuestionId");
					this.OnQuestionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="NVarChar(600) NOT NULL", CanBeNull=false)]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="Int NOT NULL")]
		public int CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					if (this._Category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserId", DbType="Int NOT NULL")]
		public int CreatedByUserId
		{
			get
			{
				return this._CreatedByUserId;
			}
			set
			{
				if ((this._CreatedByUserId != value))
				{
					if (this._CreatedByUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCreatedByUserIdChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserId = value;
					this.SendPropertyChanged("CreatedByUserId");
					this.OnCreatedByUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViewCount", DbType="Int NOT NULL")]
		public int ViewCount
		{
			get
			{
				return this._ViewCount;
			}
			set
			{
				if ((this._ViewCount != value))
				{
					this.OnViewCountChanging(value);
					this.SendPropertyChanging();
					this._ViewCount = value;
					this.SendPropertyChanged("ViewCount");
					this.OnViewCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slug", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Slug
		{
			get
			{
				return this._Slug;
			}
			set
			{
				if ((this._Slug != value))
				{
					this.OnSlugChanging(value);
					this.SendPropertyChanging();
					this._Slug = value;
					this.SendPropertyChanged("Slug");
					this.OnSlugChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approved", DbType="Bit NOT NULL")]
		public bool Approved
		{
			get
			{
				return this._Approved;
			}
			set
			{
				if ((this._Approved != value))
				{
					this.OnApprovedChanging(value);
					this.SendPropertyChanging();
					this._Approved = value;
					this.SendPropertyChanged("Approved");
					this.OnApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewDate", DbType="DateTimeOffset")]
		public System.Nullable<System.DateTimeOffset> ReviewDate
		{
			get
			{
				return this._ReviewDate;
			}
			set
			{
				if ((this._ReviewDate != value))
				{
					this.OnReviewDateChanging(value);
					this.SendPropertyChanging();
					this._ReviewDate = value;
					this.SendPropertyChanged("ReviewDate");
					this.OnReviewDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewedByUserId", DbType="Int")]
		public System.Nullable<int> ReviewedByUserId
		{
			get
			{
				return this._ReviewedByUserId;
			}
			set
			{
				if ((this._ReviewedByUserId != value))
				{
					if (this._ReviewedByUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReviewedByUserIdChanging(value);
					this.SendPropertyChanging();
					this._ReviewedByUserId = value;
					this.SendPropertyChanged("ReviewedByUserId");
					this.OnReviewedByUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectionReason", DbType="NVarChar(MAX)")]
		public string RejectionReason
		{
			get
			{
				return this._RejectionReason;
			}
			set
			{
				if ((this._RejectionReason != value))
				{
					this.OnRejectionReasonChanging(value);
					this.SendPropertyChanging();
					this._RejectionReason = value;
					this.SendPropertyChanged("RejectionReason");
					this.OnRejectionReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalTitle", DbType="NVarChar(150)")]
		public string OriginalTitle
		{
			get
			{
				return this._OriginalTitle;
			}
			set
			{
				if ((this._OriginalTitle != value))
				{
					this.OnOriginalTitleChanging(value);
					this.SendPropertyChanging();
					this._OriginalTitle = value;
					this.SendPropertyChanged("OriginalTitle");
					this.OnOriginalTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalDetails", DbType="NVarChar(600)")]
		public string OriginalDetails
		{
			get
			{
				return this._OriginalDetails;
			}
			set
			{
				if ((this._OriginalDetails != value))
				{
					this.OnOriginalDetailsChanging(value);
					this.SendPropertyChanging();
					this._OriginalDetails = value;
					this.SendPropertyChanged("OriginalDetails");
					this.OnOriginalDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Question_DraftAnswer", Storage="_DraftAnswers", ThisKey="QuestionId", OtherKey="QuestionId")]
		public EntitySet<DraftAnswer> DraftAnswers
		{
			get
			{
				return this._DraftAnswers;
			}
			set
			{
				this._DraftAnswers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Question_Answer", Storage="_Answers", ThisKey="QuestionId", OtherKey="QuestionId")]
		public EntitySet<Answer> Answers
		{
			get
			{
				return this._Answers;
			}
			set
			{
				this._Answers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Category_Question", Storage="_Category", ThisKey="CategoryId", OtherKey="CategoryId", IsForeignKey=true)]
		public Category Category
		{
			get
			{
				return this._Category.Entity;
			}
			set
			{
				Category previousValue = this._Category.Entity;
				if (((previousValue != value) 
							|| (this._Category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Category.Entity = null;
						previousValue.Questions.Remove(this);
					}
					this._Category.Entity = value;
					if ((value != null))
					{
						value.Questions.Add(this);
						this._CategoryId = value.CategoryId;
					}
					else
					{
						this._CategoryId = default(int);
					}
					this.SendPropertyChanged("Category");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Question", Storage="_CreatedByUser", ThisKey="CreatedByUserId", OtherKey="UserId", IsForeignKey=true)]
		public User CreatedByUser
		{
			get
			{
				return this._CreatedByUser.Entity;
			}
			set
			{
				User previousValue = this._CreatedByUser.Entity;
				if (((previousValue != value) 
							|| (this._CreatedByUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CreatedByUser.Entity = null;
						previousValue.CreatedQuestions.Remove(this);
					}
					this._CreatedByUser.Entity = value;
					if ((value != null))
					{
						value.CreatedQuestions.Add(this);
						this._CreatedByUserId = value.UserId;
					}
					else
					{
						this._CreatedByUserId = default(int);
					}
					this.SendPropertyChanged("CreatedByUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Question1", Storage="_ReviewedByUser", ThisKey="ReviewedByUserId", OtherKey="UserId", IsForeignKey=true)]
		public User ReviewedByUser
		{
			get
			{
				return this._ReviewedByUser.Entity;
			}
			set
			{
				User previousValue = this._ReviewedByUser.Entity;
				if (((previousValue != value) 
							|| (this._ReviewedByUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ReviewedByUser.Entity = null;
						previousValue.ReviewedQuestions.Remove(this);
					}
					this._ReviewedByUser.Entity = value;
					if ((value != null))
					{
						value.ReviewedQuestions.Add(this);
						this._ReviewedByUserId = value.UserId;
					}
					else
					{
						this._ReviewedByUserId = default(Nullable<int>);
					}
					this.SendPropertyChanged("ReviewedByUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DraftAnswers(DraftAnswer entity)
		{
			this.SendPropertyChanging();
			entity.Question = this;
		}
		
		private void detach_DraftAnswers(DraftAnswer entity)
		{
			this.SendPropertyChanging();
			entity.Question = null;
		}
		
		private void attach_Answers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.Question = this;
		}
		
		private void detach_Answers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.Question = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Answer")]
	public partial class Answer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AnswerId;
		
		private int _QuestionId;
		
		private string _Details;
		
		private System.DateTimeOffset _CreatedOn;
		
		private bool _Approved;
		
		private int _CreatedByUserId;
		
		private System.Nullable<System.DateTimeOffset> _ReviewDate;
		
		private System.Nullable<int> _ReviewedByUserId;
		
		private string _RejectionReason;
		
		private string _References;
		
		private string _OriginalDetails;
		
		private System.Nullable<int> _PublisherId;
		
		private bool _RecommendApproval;
		
		private EntityRef<User> _CreatedByUser;
		
		private EntityRef<Question> _Question;
		
		private EntityRef<User> _ReviewedByUser;
		
		private EntityRef<Publisher> _Publisher;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAnswerIdChanging(int value);
    partial void OnAnswerIdChanged();
    partial void OnQuestionIdChanging(int value);
    partial void OnQuestionIdChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnCreatedOnChanging(System.DateTimeOffset value);
    partial void OnCreatedOnChanged();
    partial void OnApprovedChanging(bool value);
    partial void OnApprovedChanged();
    partial void OnCreatedByUserIdChanging(int value);
    partial void OnCreatedByUserIdChanged();
    partial void OnReviewDateChanging(System.Nullable<System.DateTimeOffset> value);
    partial void OnReviewDateChanged();
    partial void OnReviewedByUserIdChanging(System.Nullable<int> value);
    partial void OnReviewedByUserIdChanged();
    partial void OnRejectionReasonChanging(string value);
    partial void OnRejectionReasonChanged();
    partial void OnReferencesChanging(string value);
    partial void OnReferencesChanged();
    partial void OnOriginalDetailsChanging(string value);
    partial void OnOriginalDetailsChanged();
    partial void OnPublisherIdChanging(System.Nullable<int> value);
    partial void OnPublisherIdChanged();
    partial void OnRecommendApprovalChanging(bool value);
    partial void OnRecommendApprovalChanged();
    #endregion
		
		public Answer()
		{
			this._CreatedByUser = default(EntityRef<User>);
			this._Question = default(EntityRef<Question>);
			this._ReviewedByUser = default(EntityRef<User>);
			this._Publisher = default(EntityRef<Publisher>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AnswerId
		{
			get
			{
				return this._AnswerId;
			}
			set
			{
				if ((this._AnswerId != value))
				{
					this.OnAnswerIdChanging(value);
					this.SendPropertyChanging();
					this._AnswerId = value;
					this.SendPropertyChanged("AnswerId");
					this.OnAnswerIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="Int NOT NULL")]
		public int QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					if (this._Question.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnQuestionIdChanging(value);
					this.SendPropertyChanging();
					this._QuestionId = value;
					this.SendPropertyChanged("QuestionId");
					this.OnQuestionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTimeOffset NOT NULL")]
		public System.DateTimeOffset CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Approved", DbType="Bit NOT NULL")]
		public bool Approved
		{
			get
			{
				return this._Approved;
			}
			set
			{
				if ((this._Approved != value))
				{
					this.OnApprovedChanging(value);
					this.SendPropertyChanging();
					this._Approved = value;
					this.SendPropertyChanged("Approved");
					this.OnApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserId", DbType="Int NOT NULL")]
		public int CreatedByUserId
		{
			get
			{
				return this._CreatedByUserId;
			}
			set
			{
				if ((this._CreatedByUserId != value))
				{
					if (this._CreatedByUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCreatedByUserIdChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserId = value;
					this.SendPropertyChanged("CreatedByUserId");
					this.OnCreatedByUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewDate", DbType="DateTimeOffset")]
		public System.Nullable<System.DateTimeOffset> ReviewDate
		{
			get
			{
				return this._ReviewDate;
			}
			set
			{
				if ((this._ReviewDate != value))
				{
					this.OnReviewDateChanging(value);
					this.SendPropertyChanging();
					this._ReviewDate = value;
					this.SendPropertyChanged("ReviewDate");
					this.OnReviewDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReviewedByUserId", DbType="Int")]
		public System.Nullable<int> ReviewedByUserId
		{
			get
			{
				return this._ReviewedByUserId;
			}
			set
			{
				if ((this._ReviewedByUserId != value))
				{
					if (this._ReviewedByUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnReviewedByUserIdChanging(value);
					this.SendPropertyChanging();
					this._ReviewedByUserId = value;
					this.SendPropertyChanged("ReviewedByUserId");
					this.OnReviewedByUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RejectionReason", DbType="NVarChar(MAX)")]
		public string RejectionReason
		{
			get
			{
				return this._RejectionReason;
			}
			set
			{
				if ((this._RejectionReason != value))
				{
					this.OnRejectionReasonChanging(value);
					this.SendPropertyChanging();
					this._RejectionReason = value;
					this.SendPropertyChanged("RejectionReason");
					this.OnRejectionReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[References]", Storage="_References", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string References
		{
			get
			{
				return this._References;
			}
			set
			{
				if ((this._References != value))
				{
					this.OnReferencesChanging(value);
					this.SendPropertyChanging();
					this._References = value;
					this.SendPropertyChanged("References");
					this.OnReferencesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalDetails", DbType="NVarChar(MAX)")]
		public string OriginalDetails
		{
			get
			{
				return this._OriginalDetails;
			}
			set
			{
				if ((this._OriginalDetails != value))
				{
					this.OnOriginalDetailsChanging(value);
					this.SendPropertyChanging();
					this._OriginalDetails = value;
					this.SendPropertyChanged("OriginalDetails");
					this.OnOriginalDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublisherId")]
		public System.Nullable<int> PublisherId
		{
			get
			{
				return this._PublisherId;
			}
			set
			{
				if ((this._PublisherId != value))
				{
					if (this._Publisher.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPublisherIdChanging(value);
					this.SendPropertyChanging();
					this._PublisherId = value;
					this.SendPropertyChanged("PublisherId");
					this.OnPublisherIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecommendApproval")]
		public bool RecommendApproval
		{
			get
			{
				return this._RecommendApproval;
			}
			set
			{
				if ((this._RecommendApproval != value))
				{
					this.OnRecommendApprovalChanging(value);
					this.SendPropertyChanging();
					this._RecommendApproval = value;
					this.SendPropertyChanged("RecommendApproval");
					this.OnRecommendApprovalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Answer", Storage="_CreatedByUser", ThisKey="CreatedByUserId", OtherKey="UserId", IsForeignKey=true)]
		public User CreatedByUser
		{
			get
			{
				return this._CreatedByUser.Entity;
			}
			set
			{
				User previousValue = this._CreatedByUser.Entity;
				if (((previousValue != value) 
							|| (this._CreatedByUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CreatedByUser.Entity = null;
						previousValue.CreatedAnswers.Remove(this);
					}
					this._CreatedByUser.Entity = value;
					if ((value != null))
					{
						value.CreatedAnswers.Add(this);
						this._CreatedByUserId = value.UserId;
					}
					else
					{
						this._CreatedByUserId = default(int);
					}
					this.SendPropertyChanged("CreatedByUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Question_Answer", Storage="_Question", ThisKey="QuestionId", OtherKey="QuestionId", IsForeignKey=true)]
		public Question Question
		{
			get
			{
				return this._Question.Entity;
			}
			set
			{
				Question previousValue = this._Question.Entity;
				if (((previousValue != value) 
							|| (this._Question.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Question.Entity = null;
						previousValue.Answers.Remove(this);
					}
					this._Question.Entity = value;
					if ((value != null))
					{
						value.Answers.Add(this);
						this._QuestionId = value.QuestionId;
					}
					else
					{
						this._QuestionId = default(int);
					}
					this.SendPropertyChanged("Question");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Answer1", Storage="_ReviewedByUser", ThisKey="ReviewedByUserId", OtherKey="UserId", IsForeignKey=true)]
		public User ReviewedByUser
		{
			get
			{
				return this._ReviewedByUser.Entity;
			}
			set
			{
				User previousValue = this._ReviewedByUser.Entity;
				if (((previousValue != value) 
							|| (this._ReviewedByUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ReviewedByUser.Entity = null;
						previousValue.ReviewedAnswers.Remove(this);
					}
					this._ReviewedByUser.Entity = value;
					if ((value != null))
					{
						value.ReviewedAnswers.Add(this);
						this._ReviewedByUserId = value.UserId;
					}
					else
					{
						this._ReviewedByUserId = default(Nullable<int>);
					}
					this.SendPropertyChanged("ReviewedByUser");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publisher_Answer", Storage="_Publisher", ThisKey="PublisherId", OtherKey="PublisherId", IsForeignKey=true)]
		public Publisher Publisher
		{
			get
			{
				return this._Publisher.Entity;
			}
			set
			{
				Publisher previousValue = this._Publisher.Entity;
				if (((previousValue != value) 
							|| (this._Publisher.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Publisher.Entity = null;
						previousValue.Answers.Remove(this);
					}
					this._Publisher.Entity = value;
					if ((value != null))
					{
						value.Answers.Add(this);
						this._PublisherId = value.PublisherId;
					}
					else
					{
						this._PublisherId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Publisher");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Publisher")]
	public partial class Publisher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PublisherId;
		
		private string _Name;
		
		private EntitySet<User> _Users;
		
		private EntitySet<Answer> _Answers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPublisherIdChanging(int value);
    partial void OnPublisherIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Publisher()
		{
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			this._Answers = new EntitySet<Answer>(new Action<Answer>(this.attach_Answers), new Action<Answer>(this.detach_Answers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublisherId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PublisherId
		{
			get
			{
				return this._PublisherId;
			}
			set
			{
				if ((this._PublisherId != value))
				{
					this.OnPublisherIdChanging(value);
					this.SendPropertyChanging();
					this._PublisherId = value;
					this.SendPropertyChanged("PublisherId");
					this.OnPublisherIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publisher_User", Storage="_Users", ThisKey="PublisherId", OtherKey="PublisherId")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Publisher_Answer", Storage="_Answers", ThisKey="PublisherId", OtherKey="PublisherId")]
		public EntitySet<Answer> Answers
		{
			get
			{
				return this._Answers;
			}
			set
			{
				this._Answers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Publisher = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Publisher = null;
		}
		
		private void attach_Answers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.Publisher = this;
		}
		
		private void detach_Answers(Answer entity)
		{
			this.SendPropertyChanging();
			entity.Publisher = null;
		}
	}
}
#pragma warning restore 1591
