<?xml version="1.0" encoding="utf-8"?><Database Name="Lawspot" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Region" Member="Regions">
    <Type Name="Region">
      <Column Name="RegionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Region_User" Member="Users" ThisKey="RegionId" OtherKey="RegionId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Migrations" Member="Migrations">
    <Type Name="Migration">
      <Column Name="MigrationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RunAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DraftAnswer" Member="DraftAnswers">
    <Type Name="DraftAnswer">
      <Column Name="DraftAnswerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[References]" Member="References" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedOn" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Question_DraftAnswer" Member="Question" ThisKey="QuestionId" OtherKey="QuestionId" Type="Question" IsForeignKey="true" />
      <Association Name="User_DraftAnswer" Member="CreatedByUser" ThisKey="CreatedByUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ApprovedQuestionCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnsweredQuestionCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Question" Member="Questions" ThisKey="CategoryId" OtherKey="CategoryId" Type="Question" />
      <Association Name="Category_User" Member="Users" ThisKey="CategoryId" OtherKey="SpecialisationCategoryId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Questions">
    <Type Name="Question">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(600) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="ReviewDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="ReviewedByUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RejectionReason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OriginalTitle" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="OriginalDetails" Type="System.String" DbType="NVarChar(600)" CanBeNull="true" />
      <Column Name="Status" Type="Lawspot.Backend.QuestionStatus" CanBeNull="false" />
      <Association Name="Question_DraftAnswer" Member="DraftAnswers" ThisKey="QuestionId" OtherKey="QuestionId" Type="DraftAnswer" />
      <Association Name="Question_Answer" Member="Answers" ThisKey="QuestionId" OtherKey="QuestionId" Type="Answer" />
      <Association Name="Category_Question" Member="Category" ThisKey="CategoryId" OtherKey="CategoryId" Type="Category" IsForeignKey="true" />
      <Association Name="User_Question" Member="CreatedByUser" ThisKey="CreatedByUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="User_Question1" Member="ReviewedByUser" ThisKey="ReviewedByUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="ConflictDeclaration_Question" Member="ConflictDeclaration" ThisKey="QuestionId" OtherKey="QuestionId" Type="ConflictDeclaration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Answer" Member="Answers">
    <Type Name="Answer">
      <Column Name="AnswerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="CreatedByUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReviewDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="ReviewedByUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RejectionReason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[References]" Member="References" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="OriginalDetails" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PublisherId" Type="System.Int32" CanBeNull="true" />
      <Column Name="Status" Type="Lawspot.Backend.AnswerStatus" CanBeNull="false" />
      <Association Name="Question_Answer" Member="Question" ThisKey="QuestionId" OtherKey="QuestionId" Type="Question" IsForeignKey="true" />
      <Association Name="Publisher_Answer" Member="Publisher" ThisKey="PublisherId" OtherKey="PublisherId" Type="Publisher" IsForeignKey="true" />
      <Association Name="User_Answer" Member="CreatedByUser" ThisKey="CreatedByUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="User_Answer1" Member="ReviewedByUser" ThisKey="ReviewedByUserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Publisher" Member="Publishers">
    <Type Name="Publisher">
      <Column Name="PublisherId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShortDescription" Type="System.String" DbType="NVarChar(250) NULL" CanBeNull="true" />
      <Column Name="LongDescription" Type="System.String" DbType="NVarChar(MAX) NULL" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVARCHAR(256) NULL" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVARCHAR(50) NULL" CanBeNull="true" />
      <Column Name="WebsiteUri" Type="System.String" DbType="NVARCHAR(256) NULL" CanBeNull="true" />
      <Column Name="PhysicalAddress" Type="System.String" DbType="NVARCHAR(256) NULL" CanBeNull="true" />
      <Column Name="Logo" Type="System.Byte[]" DbType="VARBINARY(MAX) NULL" CanBeNull="true" UpdateCheck="Never" IsDelayLoaded="true" />
      <Association Name="Publisher_Answer" Member="Answers" ThisKey="PublisherId" OtherKey="PublisherId" Type="Answer" />
      <Association Name="Publisher_User" Member="Users" ThisKey="PublisherId" OtherKey="PublisherId" Type="User" />
      <Association Name="Publisher_PublisherCategory" Member="PublisherCategories" ThisKey="PublisherId" OtherKey="PublisherId" Type="PublisherCategory" />
    </Type>
  </Table>
  <Table Name="dbo.EventStream" Member="Events">
    <Type Name="Event">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="Lawspot.Backend.EventType" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Event" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="RegionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedOn" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="CanAnswerQuestions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanVetQuestions" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanVetAnswers" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CanVetLawyers" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EmailValidated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EmailValidationToken" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CanAdminister" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastLogInDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="LogInCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LogInIpAddress" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="CommunityServicesCardNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ResetPasswordToken" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ResetPasswordTokenExpiry" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="PublisherId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="YearOfAdmission" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpecialisationCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ApprovedAsLawyer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReviewDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="ReviewedByUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RejectionReason" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_DraftAnswer" Member="DraftAnswers" ThisKey="UserId" OtherKey="CreatedByUserId" Type="DraftAnswer" />
      <Association Name="User_Question" Member="Questions" ThisKey="UserId" OtherKey="CreatedByUserId" Type="Question" />
      <Association Name="User_Question1" Member="Questions1" ThisKey="UserId" OtherKey="ReviewedByUserId" Type="Question" />
      <Association Name="User_Answer" Member="Answers" ThisKey="UserId" OtherKey="CreatedByUserId" Type="Answer" />
      <Association Name="User_Answer1" Member="Answers1" ThisKey="UserId" OtherKey="ReviewedByUserId" Type="Answer" />
      <Association Name="User_Event" Member="Events" ThisKey="UserId" OtherKey="UserId" Type="Event" />
      <Association Name="Category_User" Member="SpecialisationCategory" Storage="_Category" ThisKey="SpecialisationCategoryId" OtherKey="CategoryId" Type="Category" IsForeignKey="true" />
      <Association Name="Publisher_User" Member="Publisher" ThisKey="PublisherId" OtherKey="PublisherId" Type="Publisher" IsForeignKey="true" />
      <Association Name="Region_User" Member="Region" ThisKey="RegionId" OtherKey="RegionId" Type="Region" IsForeignKey="true" />
      <Association Name="ConflictDeclaration_User" Member="ConflictDeclaration" ThisKey="UserId" OtherKey="UserId" Type="ConflictDeclaration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="ConflictDeclarations">
    <Type Name="ConflictDeclaration">
      <Column Name="DeclarationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="ConflictDeclaration_Question" Member="Questions" ThisKey="QuestionId" OtherKey="QuestionId" Type="Question" />
      <Association Name="ConflictDeclaration_User" Member="Users" ThisKey="UserId" OtherKey="UserId" Type="User" />
    </Type>
  </Table>
  <Table Name="" Member="PublisherCategories">
    <Type Name="PublisherCategory">
      <Column Name="PublisherId" Type="System.Int32" DbType="Int" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Publisher_PublisherCategory" Member="Publisher" ThisKey="PublisherId" OtherKey="PublisherId" Type="Publisher" IsForeignKey="true" />
      <Association Name="Category_PublisherCategory" Member="Category" ThisKey="CategoryId" OtherKey="CategoryId" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
</Database>