CREATE TABLE DraftAnswer (
	DraftAnswerId INT NOT NULL IDENTITY CONSTRAINT PK_DraftAnswer PRIMARY KEY,
	QuestionId INT NOT NULL CONSTRAINT FK_DraftAnswer_QuestionId FOREIGN KEY REFERENCES Question(QuestionId),
	Details NVARCHAR(MAX) NOT NULL,
	[References] NVARCHAR(MAX) NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL,
	CreatedByUserId INT NOT NULL CONSTRAINT FK_DraftAnswer_CreatedByUserId FOREIGN KEY REFERENCES [User](UserId),
	UpdatedOn DATETIMEOFFSET NOT NULL
)