ALTER TABLE [User]
ADD LastLogInDate DATETIMEOFFSET NULL,
LogInCount INT NULL,
LogInIpAddress VARCHAR(45) NULL
GO

UPDATE [User]
SET LogInCount = 0

ALTER TABLE [User]
ALTER COLUMN LogInCount INT NOT NULL